//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizatorProslava.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrganizatorProslavaEntities : DbContext
    {
        public OrganizatorProslavaEntities()
            : base("name=OrganizatorProslavaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Proizvod> Proizvods { get; set; }
        public virtual DbSet<Saradnik> Saradniks { get; set; }
        public virtual DbSet<TipSaradnika> TipSaradnikas { get; set; }
        public virtual DbSet<Zabava> Zabavas { get; set; }
        public virtual DbSet<Zabava_Poruke> Zabava_Poruke { get; set; }
        public virtual DbSet<Zabava_Proizvod> Zabava_Proizvod { get; set; }
        public virtual DbSet<SalaSto> SalaStoes { get; set; }
        public virtual DbSet<ZabavaSalaSto> ZabavaSalaStoes { get; set; }
        public virtual DbSet<ZabavaSalaStoGost> ZabavaSalaStoGosts { get; set; }
    }
}
