//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizatorProslava.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaSto
    {
        public int ID { get; set; }
        public int ProizvodID { get; set; }
        public string Opis { get; set; }
        public Nullable<int> BrojMesta { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
    }
}
