//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizatorProslava.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zabava
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zabava()
        {
            this.Saradniks = new HashSet<Saradnik>();
        }
    
        public int ID { get; set; }
        public string Tip { get; set; }
        public System.DateTime DatumProslave { get; set; }
        public int Trajanje { get; set; }
        public string Grad { get; set; }
        public string Tema { get; set; }
        public int BrojGostiju { get; set; }
        public bool VrstaBudzeta { get; set; }
        public double Budzet { get; set; }
        public string SpisakGostiju { get; set; }
        public int Status { get; set; }
        public string DodatneZelje { get; set; }
        public Nullable<int> Organizator { get; set; }
        public int Kreator { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Korisnik Korisnik1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saradnik> Saradniks { get; set; }
    }
}
